spring:
  datasource:
    url: jdbc:mysql://47.237.28.208:3306/cloak?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: zhouxing
    password: zhou1994121888
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 8 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: Glowe_redis
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.macro.mall: debug