spring:
  datasource:
    url:
    username:
    password:
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 8 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info